language: objective-c
osx_image: xcode8
notifications:
  email:
    - dudl@qq.com
# after_success:
#     - bash <(curl -s https://codecov.io/bash)

podfile: Example/Podfile
script:
  xcodebuild
  -workspace Example/MLImageBrowser.xcworkspace
  -scheme MLImageBrowser 
  -sdk iphonesimulator 
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO